### ISSUE TITLE
optimize bundle size

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-governance#110]

**Comment by kenodressel** [comment]
Suggestions:
- Replace Axios with native fetch (saves about 1.4%)
- Use PurgeCSS on aepp components repo (aepp-components css are curr. 6.4% of total bundle)
- Narrow down core-js polyfills used and include them (core-js is ~12%) (see https://github.com/zloirock/core-js/issues/388)

Since around 60+% of our bundle is the js-sdk I already made some size reduction suggestions there:
- https://github.com/aeternity/aepp-sdk-js/issues/435
- https://github.com/aeternity/aepp-sdk-js/issues/805 
But we should consider working with the sdk-team to reduce their dependency size as this is still the main reason our bundle is so big.
